apiVersion: batch/v1 
kind: Job 
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: thanos-metrics-analyzer 
spec:
  template:
    metadata:
      labels:
        name: thanos-metrics-analyzer 
    spec:
      containers:
      - env:
        - name: LOGROOT 
          value: "/logs"
        - name: THANOS_URLS_JSON
          value: /input/thanos.json
        - name: GRAFANA_DASHBOARD_UID
          value: "85a562078cdf77779eaa1add43ccec1e"
        image: quay.io/stolostron/thanos-metrics-analyzer:a1011 
        name: thanos-metrics-analyzer
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false 
        volumeMounts:
        - mountPath: /logs
          name: thanos-metrics-analyzer 
        - mountPath: /input
          name: thanos-urls
      restartPolicy: Never
      imagePullSecrets:
      - name: thanos-metrics-analyzer-pull-secret
      serviceAccount: thanos-metrics-analyzer
      serviceAccountName: thanos-metrics-analyzer
      volumes:
      - name: thanos-metrics-analyzer
        persistentVolumeClaim:
          claimName: thanos-metrics-analyzer
      - name: thanos-urls
        configMap:
          name: thanos-urls
