apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-metrics-analyzer 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-csi  #update your storeageclass here 
  volumeMode: Filesystem
