apiVersion: v1 
kind: Pod
metadata:
  name: sleep-thanos-metric-analyzer
spec:
  containers:
    - image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      name: web-app
      command: ["sh", "-c", "sleep infinity"]
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 8443
        protocol: TCP
      resources: 
        limits:
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
      - mountPath: /logs
        name: thanos-metrics-analyzer 
  volumes:
  - name: thanos-metrics-analyzer
    persistentVolumeClaim:
      claimName: thanos-metrics-analyzer