apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vm-prometheus-rules
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: prometheus-rules-policy
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - openshift-monitoring
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: monitoring.coreos.com/v1
                kind: PrometheusRule
                metadata:
                  name: acm-right-sizing-rules
                  namespace: openshift-monitoring
                spec:
                  groups:
                    - name: acm-vm-right-sizing-namespace-5m.rule
                      interval: 5m
                      rules:
                        - record: 'acm_vm_rs_test:namespace:cpu_request:5m'
                          expr: |
                            max_over_time(
                              sum(
                                kubevirt_vm_resource_requests{
                                  name!='',
                                  namespace!~'openshift.*|xyz.*',
                                  container!='',
                                  unit='cores',
                                  resource='cpu'
                                } * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (name, namespace)[5m:])
                        - record: 'acm_vm_rs_test:namespace:memory_request:5m'
                          expr: |
                            max_over_time(
                              sum(
                                kubevirt_vm_resource_requests{
                                  name!='',
                                  namespace!~'openshift.*|xyz.*',
                                  container!='',
                                  resource='memory'
                                } * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (name, namespace)[5m:])
                        - record: 'acm_vm_rs_test:namespace:cpu_usage:5m'
                          expr: |
                            max_over_time(
                              sum(
                                rate(
                                  kubevirt_vmi_cpu_usage_seconds_total{
                                    name!='',
                                    namespace!~'openshift.*',
                                    container!=''
                                  }[5m:]
                                ) * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (name, namespace)[5m:])
                        - record: 'acm_vm_rs_test:namespace:memory_usage:5m'
                          expr: |
                            max_over_time(
                              sum(rate(
                                kubevirt_vmi_memory_used_bytes{name!='', namespace!~'openshift.*', container!=''}[5m:]
                              ) 
                              * on (namespace) group_left()
                              (kube_namespace_labels{label_env=~"prod|dev"} or kube_namespace_labels{label_env=''})
                            ) by (name, namespace)[5m:]
                            )
                    - name: acm-vm-right-sizing-namespace-1d.rules
                      interval: 15m
                      rules:
                        - record: 'acm_vm_rs_test:namespace:cpu_request'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:cpu_request:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:namespace:cpu_usage'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:cpu_usage:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:namespace:memory_request'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:memory_request:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:namespace:memory_usage'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:memory_usage:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:namespace:cpu_recommendation'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:cpu_usage{profile="Max OverAll"}[1d]) * (1 + (10/100))
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:namespace:memory_recommendation'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:memory_usage{profile="Max OverAll"}[1d]) * (1 + (10/100))
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                    - name: acm-vm-right-sizing-cluster-5m.rule
                      interval: 5m
                      rules:
                        - record: 'acm_vm_rs_test:cluster:cpu_request:5m'
                          expr: |
                            max_over_time(
                              sum(
                                kubevirt_vm_resource_requests{
                                  name!='',
                                  namespace!~'openshift.*|xyz.*',
                                  container!='',
                                  unit='cores',
                                  resource='cpu'
                                } * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (cluster)[5m:])
                        - record: 'acm_vm_rs_test:cluster:memory_request:5m'
                          expr: |
                            max_over_time(
                              sum(
                                kubevirt_vm_resource_requests{
                                  name!='',
                                  namespace!~'openshift.*|xyz.*',
                                  container!='',
                                  resource='memory'
                                } * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (cluster)[5m:])
                        - record: 'acm_vm_rs_test:cluster:cpu_usage:5m'
                          expr: |
                            max_over_time(
                              sum(
                                rate(
                                  kubevirt_vmi_cpu_usage_seconds_total{
                                    name!='',
                                    namespace!~'openshift.*',
                                    container!=''
                                  }[5m:]
                                ) * on (namespace) group_left()
                                (kube_namespace_labels{
                                  label_env=~"prod|dev|",
                                  label_kubernetes_io_metadata_name!=''
                                })
                              ) by (cluster)[5m:])
                        - record: 'acm_vm_rs_test:cluster:memory_usage:5m'
                          expr: |
                            max_over_time(
                              sum(rate(
                                kubevirt_vmi_memory_used_bytes{name!='', namespace!~'openshift.*', container!=''}[5m:]
                              ) 
                              * on (namespace) group_left()
                              (kube_namespace_labels{label_env=~"prod|dev"} or kube_namespace_labels{label_env=''})
                            ) by (cluster)[5m:]
                            )
                    - name: acm-vm-right-sizing-cluster-1d.rules
                      interval: 15m
                      rules:
                        - record: 'acm_vm_rs_test:cluster:cpu_request'
                          expr: |
                            max_over_time(acm_vm_rs_test:cluster:cpu_request:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:cluster:cpu_usage'
                          expr: |
                            max_over_time(acm_vm_rs_test:cluster:cpu_usage:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:cluster:memory_request'
                          expr: |
                            max_over_time(acm_vm_rs_test:cluster:memory_request:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:cluster:memory_usage'
                          expr: |
                            max_over_time(acm_vm_rs_test:cluster:memory_usage:5m[1d])
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:cluster:cpu_recommendation'
                          expr: |
                            max_over_time(acm_vm_rs_test:cluster:cpu_usage{profile="Max OverAll"}[1d]) * (1 + (10/100))
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                        - record: 'acm_vm_rs_test:cluster:memory_recommendation'
                          expr: |
                            max_over_time(acm_vm_rs_test:namespace:memory_usage{profile="Max OverAll"}[1d]) * (1 + (10/100))
                          labels:
                            aggregation: 1d
                            profile: Max OverAll
                                        
